# Configuration for Yarn Berry (v4.x)

# Set the compression level for Yarn archives (e.g., tarballs). 
# Options: mixed, maximum, or none. "mixed" is a balanced choice.
compressionLevel: mixed

# Enable caching across Yarn projects globally.
enableGlobalCache: true

# Define the global folder for storing Yarn's global cache.
globalFolder: .yarn/berry

# Use `node-modules` linker to generate `node_modules` folders. 
# Alternatives: `pnp`, `pnpm`.
nodeLinker: node-modules

# Allow HTTP requests to specific hosts, useful for local development or custom registries.
unsafeHttpWhitelist:
  - localhost

# Define custom npm registry authentication and configuration.
npmRegistries:
  "//localhost:4873":
    npmAuthToken: "${LOCAL_NPM_TOKEN-}" # Local NPM registry token.
  "//registry.npmjs.org":
    npmAuthToken: "${NPM_TOKEN-}"       # NPM registry token.

# Define specific configurations for scoped packages.
npmScopes:
  layerzerolabs:
    npmAlwaysAuth: true                      # Always authenticate for this scope.
    npmPublishRegistry: "${NPM_REGISTRY-https://registry.npmjs.org}" # Custom publish registry.
    npmRegistryServer: "${NPM_REGISTRY-https://registry.npmjs.org}"  # Custom registry server.

# Path to the specific Yarn version to use for this project.
yarnPath: .yarn/releases/yarn-4.0.2.cjs
